org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false

addon_id=bluemap-mekanism
addon_name=BlueMap Mekanism Add-on
addon_version=0.1.0-alpha.1
addon_group=io.github.jan-guenter
artifact_id=bluemap-mekanism-addon
bluemap_version=5.22-agent.backport-5.22-mc1.21.1-2
accepted_jar_size=78688
accepted_jar_sha256=fc0b0144dcd3dd5ec24747961bd57960f5f00d699c7bb5dc67975739fb0d61c7
